from openpyxl import Workbook
wb = Workbook()
ws = wb.active
ws.title = 'Test Cases'
headers = ['ID','Module','Test Scenario','Test Steps','Preconditions / Input Data','Expected Result','Notes']
ws.append(headers)
rows = [
    ['TC001','Splash & Onboarding','App launches to Splash screen','Launch the app','Fresh install or app closed','Splash screen displays, then navigates to Language selection after 3s',''],
    ['TC002','Language Selection','Select supported language','On Language screen, choose a language and continue','App on Language selection screen','App applies locale, then navigates to Login screen','Verify app strings change if multiple languages supported'],
    ['TC003','Login - Empty credentials','Attempt login without email/password','Open Login screen, tap Login with empty fields','Login screen displayed','Toast shows "Please fill all fields"',''],
    ['TC004','Login - Invalid email format','Enter invalid email and valid password','Input "user" into email, valid password, tap Login','Login fails','Toast shows "Please fill all fields" or invalid message when empty check fails','Depending on validation flow'],
    ['TC005','Login - Wrong credentials','Enter incorrect account details','Input existing email with wrong password, tap Login','Login fails','Toast shows "Invalid credentials"',''],
    ['TC006','Login - No internet','Try login while network unavailable','Disable network, enter valid credentials, tap Login','No internet dialog appears','Dialog title "No Internet Connection" and OK button',''],
    ['TC007','Login - Successful patient','Login with valid patient credentials','Enter valid email/password for patient, tap Login','Login succeeds','Navigates to DashboardActivity, session saved, reminders scheduled',''],
    ['TC008','Login - Successful admin','Login with valid admin credentials','Enter valid admin email/password, tap Login','Login succeeds','Navigates to AdminDashboardActivity, session saved',''],
    ['TC009','Register - Empty fields','Attempt register with blank inputs','Open Register screen, tap Register with empty fields','Validation fails','Field-level error on first required field',''],
    ['TC010','Register - Invalid email','Submit registration with invalid email','Provide name, invalid email, valid password, phone, tap Register','Validation fails','Email field shows "Enter a valid email address"',''],
    ['TC011','Register - Short password','Submit registration with password <6 chars','Provide valid name/email/password, 5-char password, valid phone, tap Register','Validation fails','Password field shows "Password must be at least 6 characters"',''],
    ['TC012','Register - Invalid phone','Submit registration with non-numeric/short phone','Provide valid name/email/password, phone "12345" or letters, tap Register','Validation fails','Phone field shows "Enter a valid 10-digit phone number"',''],
    ['TC013','Register - No internet','Try to register offline','Disable network, fill valid registration form, tap Register','No internet dialog appears','Dialog asks to connect to WiFi and make sure XAMPP is running',''],
    ['TC014','Register - Successful patient','Complete registration with valid data','Enter valid name/email/password/phone and tap Register','Registration succeeds','Toast confirms success and navigates to Login screen',''],
    ['TC015','Forgot Password - empty email','Submit forgot password blank','Open Forgot Password screen, tap Send Reset without entering email','Validation fails','Toast shows "Please enter your email"',''],
    ['TC016','Forgot Password - invalid email format','Submit invalid email','Enter invalid email, tap Send Reset','Validation or server rejects','Toast shows error or connection message','Depends on backend response'],
    ['TC017','Forgot Password - valid email','Submit registered email','Enter registered email, tap Send Reset','Reset request sent','Toast shows success message and activity closes',''],
    ['TC018','Session persistence','App relaunch after patient login','Login as patient, close app, reopen app','Session exists','App should go directly to DashboardActivity from Splash',''],
    ['TC019','Logout patient','Logout from patient dashboard','On Dashboard tap Logout and confirm','Session cleared','Navigates to LanguageActivity and removes back stack',''],
    ['TC020','Logout admin','Logout from admin dashboard','On Admin Dashboard tap Logout and confirm','Session cleared','Navigates to LanguageActivity and removes back stack',''],
    ['TC021','Patient Dashboard - welcome text','Verify welcome message on dashboard','Login as patient and open Dashboard','Dashboard loads','Displays "Welcome, <name>"',''],
    ['TC022','Patient Dashboard - procedure load success','Assigned procedure loads on dashboard','Login as patient with assigned procedure','Dashboard loads','Procedure, category, description display correctly',''],
    ['TC023','Patient Dashboard - procedure load failure','Server error fetching procedure','Simulate backend error or offline while loading procedure','Dashboard loads','Shows error text and guidance to check connection',''],
    ['TC024','Patient Dashboard - appointment 1 navigation','Navigate to Baseline1 via button','Tap Appointment 1 button','Navigation occurs','Opens Baseline1Activity with procedure_id/category extras',''],
    ['TC025','Patient Dashboard - appointment 2 navigation','Navigate to Baseline2 via button','Tap Appointment 2 button','Navigation occurs','Opens Baseline2Activity with procedure_id/category extras',''],
    ['TC026','Patient Dashboard - appointment 3 navigation','Navigate to Baseline3 via button','Tap Appointment 3 button','Navigation occurs','Opens Baseline3Activity with procedure_id/category extras',''],
    ['TC027','Patient Dashboard - follow up navigation','Navigate to Baseline4 via FollowUp','Tap Follow Up button','Navigation occurs','Opens Baseline4Activity',''],
    ['TC028','Notification permission prompt','Request notifications if SDK >= Tiramisu','Launch Dashboard on Android 13+ device','Permission not granted','Prompt for POST_NOTIFICATIONS permission',''],
    ['TC029','Daily reminder scheduling','Patient login schedules reminder','Login as patient successfully','Reminder is scheduled','Notification helper creates channel and reminder scheduled',''],
    ['TC030','Admin Dashboard - patient list access','Open Patient List from admin','Tap Patient List button','Navigation occurs','Opens PatientListActivity',''],
    ['TC031','Admin Dashboard - scores access','Open Scores screen from admin','Tap Scores button','Navigation occurs','Opens ScoresActivity',''],
    ['TC032','Admin Dashboard - consent status access','Open consent status from admin','Tap Consent button','Navigation occurs','Opens ConsentStatusActivity',''],
    ['TC033','Admin Dashboard - attendance access','Open attendance screen from admin','Tap Attendance button','Navigation occurs','Opens AttendanceActivity',''],
    ['TC034','Admin Dashboard - export data','Open export screen from admin','Tap Export button','Navigation occurs','Opens ExportActivity',''],
    ['TC035','Admin Dashboard - assign procedure access','Open assign procedure from admin','Tap Assign Procedure button','Navigation occurs','Opens AssignProcedureActivity',''],
    ['TC036','Admin Dashboard - outcomes report access','Open outcomes report from admin','Tap Outcomes button','Navigation occurs','Opens OutcomesReportActivity',''],
    ['TC037','Admin Dashboard - comparator group access','Open comparator group from admin','Tap Comparator button','Navigation occurs','Opens ComparatorGroupActivity',''],
    ['TC038','Assign Procedure - patient/procedure load','Verify dropdowns populate','Open AssignProcedureActivity','Network and server available','Spinner lists fill and assign button enabled',''],
    ['TC039','Assign Procedure - assign default group','Assign procedure with intervention group selected','Select patient, procedure, intervention, tap Assign','Assignment succeeds','Toast confirms assignment successfully!',''],
    ['TC040','Assign Procedure - assign comparator group','Assign procedure with comparator group selected','Select patient, procedure, comparator, tap Assign','Assignment succeeds','Toast confirms assignment successfully!',''],
    ['TC041','Assign Procedure - load failure handling','Handle failed patient/procedure loads','Simulate backend error on GET patients or procedures','Activity still loads','Shows error toast and enables button once data load completes',''],
    ['TC042','Baseline 1 flow start','Navigate into Baseline1 and complete start','Open Baseline1Activity from dashboard','Baseline1 screen loads','Displays location-specific baseline details',''],
    ['TC043','Baseline 2 flow continuity','Navigate into Baseline2 and complete start','Open Baseline2Activity from dashboard','Baseline2 screen loads','Displays the correct appointment content',''],
    ['TC044','Baseline 3 flow continuity','Navigate into Baseline3 and complete start','Open Baseline3Activity from dashboard','Baseline3 screen loads','Displays the correct appointment content',''],
    ['TC045','Baseline 4 follow-up flow','Navigate into Baseline4 from dashboard','Open Baseline4Activity via FollowUp','Baseline4 screen loads','Displays follow-up content and saved state',''],
    ['TC046','Education module access','Open first education module from flow','Navigate to Education1Activity','Education1 screen loads','Displays education content',''],
    ['TC047','Education 2 module access','Open second education module from flow','Navigate to Education2Activity','Education2 screen loads','Displays education content',''],
    ['TC048','Education 3 module access','Open third education module from flow','Navigate to Education3Activity','Education3 screen loads','Displays education content',''],
    ['TC049','Quiz 1 start and submit','Begin Quiz1 and answer questions','Open Quiz1Activity, select answers, submit','Quiz processes answers','Navigate to next or display score',''],
    ['TC050','Quiz 2 start and submit','Begin Quiz2 and answer questions','Open Quiz2Activity, select answers, submit','Quiz processes answers','Navigate to next or display score',''],
    ['TC051','Quiz 3 start and submit','Begin Quiz3 and answer questions','Open Quiz3Activity, select answers, submit','Quiz processes answers','Navigate to next or display score',''],
    ['TC052','Counselling module access','Open counselling session screen','Navigate to Counselling1Activity','Counselling1 screen loads','Displays counselling guidance content',''],
    ['TC053','Consent form access','Open patient consent form screen','Navigate to ConsentActivity','ConsentActivity loads','Displays consent questions and actions',''],
    ['TC054','Consent status viewing','Admin views consent status','Open ConsentStatusActivity from admin dashboard','Consent status screen loads','Displays list of patients and consent statuses',''],
    ['TC055','Post-op education access','Open PostOpActivity after treatment','Navigate to PostOpActivity','PostOp screen loads','Displays post-operative instructions',''],
    ['TC056','Reinforcement content access','Open ReinforcementActivity after quizzes','Navigate to ReinforcementActivity','Reinforcement screen loads','Displays reinforcement material',''],
    ['TC057','Final assessment access','Open FinalAssessmentActivity','Navigate to FinalAssessmentActivity','Final assessment screen loads','Displays final assessment questions',''],
    ['TC058','Outcomes report access','Admin opens OutcomesReportActivity','Open Outcomes Report from admin dashboard','Outcomes Report loads','Displays performance metrics and summary',''],
    ['TC059','Comparator group access','Admin opens ComparatorGroupActivity','Open Comparator Group from admin dashboard','Comparator Group screen loads','Displays comparator group data or controls',''],
    ['TC060','Anxiety assessment access','Open AnxietyAssessmentActivity','Navigate to AnxietyAssessmentActivity','Anxiety assessment screen loads','Displays assessment questions',''],
    ['TC061','Satisfaction survey access','Open SatisfactionActivity','Navigate to SatisfactionActivity','Satisfaction screen loads','Displays satisfaction questions or feedback form',''],
    ['TC062','1-week follow-up access','Open FollowUp1WeekActivity','Navigate to FollowUp1WeekActivity','Follow up screen loads','Displays 1-week outcome evaluation',''],
    ['TC063','Procedure information access','Open ProcedureInfoActivity','Navigate to ProcedureInfoActivity','Procedure info screen loads','Displays details about the selected procedure',''],
    ['TC064','Export data function opens','Open ExportActivity from admin','Tap Export in admin dashboard','Export screen loads','Displays export controls and options',''],
    ['TC065','Attendance screen access','Open AttendanceActivity from admin','Tap Attendance in admin dashboard','Attendance screen loads','Displays attendance list or controls',''],
    ['TC066','Scores screen access','Open ScoresActivity from admin','Tap Scores in admin dashboard','Scores screen loads','Displays scores data for patients',''],
    ['TC067','Session role-based navigation','Admin login goes to admin dashboard','Login as admin and app launches','Successful login','Navigates to AdminDashboardActivity',''],
    ['TC068','Session role-based patient navigation','Patient login goes to patient dashboard','Login as patient and app launches','Successful login','Navigates to DashboardActivity',''],
    ['TC069','Locale helper persistence','Language choice persists across sessions','Select language, login, logout, relaunch app','Language selected','App continues using chosen language',''],
    ['TC070','Daily reminder cancellation','Logout should cancel reminders','Login as patient and logout','Active reminder scheduled','Reminder is canceled on logout',''],
    ['TC071','Error message on failed assignment','Server returns failure when assigning procedure','Attempt assign with backend sending error status','Assignment fails','Toast shows returned error message',''],
    ['TC072','Invalid procedure assignment handling','Attempt assign with empty patient/procedure lists','Open AssignProcedureActivity with no loaded items','Assignment not possible','Toast shows "No patients or procedures available"',''],
    ['TC073','Offline page navigation behavior','Navigate through app screens without network if local access allowed','Disable network after login and navigate','Certain screens access local content','App should not crash and should show offline warnings where appropriate',''],
    ['TC074','Notifications channel creation','App creates notification channel on login/register','Complete login or registration process','Notification channel does not exist before','Notification channel is created successfully',''],
    ['TC075','Boot receiver registration','App handles device reboot for reminders','Reboot device after schedule setup','BOOT_COMPLETED broadcast delivered','ReminderReceiver registered and can reschedule alarms',''],
    ['TC076','Back navigation after logout','Ensure back button does not return to secured screens','Logout and press Back on LanguageActivity','Back navigation triggered','App remains on LanguageActivity or exits, does not return to dashboard',''],
    ['TC077','Incorrect password error message','Login with correct email and wrong password','Enter correct email, wrong password, tap Login','Login fails','Toast says "Invalid credentials"',''],
    ['TC078','Register duplicate email handling','Register using an email already in use','Fill registration form with an existing email','Registration fails','Toast indicates email already exists or registration failed',''],
    ['TC079','Notification permission denial','Deny notification permission when prompted','Launch Dashboard on Android 13+, deny prompt','Permission denied','App continues working without crash and no daily notification sent',''],
    ['TC080','Assign procedure group toggle','Switch between intervention/comparator groups','Select each group radio button before assign','Selection changes','Correct group value sent in request body',''],
]
for row in rows:
    ws.append(row)
for col in range(1, len(headers)+1):
    ws.column_dimensions[ws.cell(row=1, column=col).column_letter].width = 20
wb.save('RootCanal_TestCases.xlsx')
print('Created RootCanal_TestCases.xlsx with', len(rows), 'test cases')
